language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -r tools/ci/requirements.txt
  - pip install -r requirements-dev.txt
# command to run tests
script:
  - python tools/ci/check_all.py
  - python tests/test_all.py
