language: python

dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

python:
  - "3.7"

matrix:
  include:
    - name: "code quality analysis: flake8"
      before_install:
        - pip install flake8
      install:
        - ""  # prevent running "pip install -r requirements.txt"
      script:
        - flake8

    - name: "pip install under Windows"
      os: "windows"
      language: "cpp"
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python3 --version 3.7.2
      install:
        - pip install -r requirements.txt
        - pip install .
      script:
        # todo: use python unittest
        - mkdir run; cd run; python -c "import vnpy.api.ctp.vnctpmd; import vnpy.api.oes.vnoes; exit(0);"

    - name: "pip install under Ubuntu: gcc-8"
      before_install:
        # C++17
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -y
      install:
        # C++17
        - sudo apt-get install -y gcc-8 g++-8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-8 90
        - sudo update-alternatives --install /usr/bin/gcc cc /usr/bin/gcc-8 90
        # Linux install script
        - bash ./install.sh
      script:
        # todo: use python unittest
        - mkdir run; cd run; python -c "import vnpy.api.ctp.vnctpmd; import vnpy.api.oes.vnoes; exit(0);"

    - name: "pip install under Ubuntu: gcc-7"
      before_install:
        # C++17
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -y
      install:
        # C++17
        - sudo apt-get install -y gcc-7 g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
        - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-7 90
        - sudo update-alternatives --install /usr/bin/gcc cc /usr/bin/gcc-7 90
        # Linux install script
        - bash ./install.sh
      script:
        # todo: use python unittest
        - mkdir run; cd run; python -c "import vnpy.api.ctp.vnctpmd; import vnpy.api.oes.vnoes; exit(0);"

